const RAKS = [
  [
    { text: "Leave" },
    { text: "a" },
    { text: "kind", className: "text-blue-500 dark:text-blue-500" },
    { text: "note", className: "text-blue-500 dark:text-blue-500" },
    { text: "for" },
    { text: "a" },
    { text: "stranger", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Help" },
    { text: "an" },
    { text: "elderly", className: "text-blue-500 dark:text-blue-500" },
    { text: "person" },
    { text: "cross" },
    { text: "the" },
    { text: "street" },
  ],
  [
    { text: "Donate" },
    { text: "unused" },
    { text: "clothing" },
    { text: "to" },
    { text: "a" },
    { text: "shelter", className: "text-blue-500 dark:text-blue-500" },
    { text: "or" },
    { text: "charity", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Write" },
    { text: "a" },
    { text: "thank" },
    { text: "you" },
    { text: "note" },
    { text: "to" },
    { text: "a" },
    { text: "mentor", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Give" },
    { text: "a" },
    { text: "compliment" },
    { text: "to" },
    { text: "a" },
    { text: "stranger", className: "text-blue-500 dark:text-blue-500" },
    { text: "today", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Plant" },
    { text: "a" },
    { text: "tree" },
    { text: "or" },
    { text: "flowers" },
    { text: "in" },
    { text: "a" },
    { text: "public" },
    { text: "area", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Volunteer" },
    { text: "at" },
    { text: "a" },
    { text: "local" },
    { text: "community", className: "text-blue-500 dark:text-blue-500" },
    { text: "center", className: "text-blue-500 dark:text-blue-500" },
    { text: "or" },
    { text: "soup" },
    { text: "kitchen" },
  ],
  [
    { text: "Offer" },
    { text: "to" },
    { text: "babysit" },
    { text: "for" },
    { text: "a" },
    { text: "friend", className: "text-blue-500 dark:text-blue-500" },
    { text: "or" },
    { text: "neighbor", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Send" },
    { text: "a" },
    { text: "care" },
    { text: "package" },
    { text: "to" },
    { text: "someone" },
    { text: "in", className: "text-blue-500 dark:text-blue-500" },
    { text: "need", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Offer" },
    { text: "to" },
    { text: "help" },
    { text: "a" },
    { text: "colleague", className: "text-blue-500 dark:text-blue-500" },
    { text: "with" },
    { text: "their" },
    { text: "workload" },
  ],
  [
    { text: "Donate" },
    { text: "books" },
    { text: "to" },
    { text: "a" },
    { text: "local" },
    { text: "library", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Say" },
    { text: "thank" },
    { text: "you" },
    { text: "to" },
    { text: "a" },
    { text: "bus", className: "text-blue-500 dark:text-blue-500" },
    { text: "driver", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Offer" },
    { text: "to" },
    { text: "run" },
    { text: "errands" },
    { text: "for" },
    { text: "an" },
    { text: "elderly", className: "text-blue-500 dark:text-blue-500" },
    { text: "neighbor", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Write" },
    { text: "a" },
    { text: "positive" },
    { text: "review" },
    { text: "for" },
    { text: "a" },
    { text: "local", className: "text-blue-500 dark:text-blue-500" },
    { text: "business", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Offer" },
    { text: "to" },
    { text: "mentor" },
    { text: "a" },
    { text: "student", className: "text-blue-500 dark:text-blue-500" },
    { text: "for" },
    { text: "free" },
  ],
  [
    { text: "Cook" },
    { text: "a" },
    { text: "meal" },
    { text: "for" },
    { text: "a" },
    { text: "family", className: "text-blue-500 dark:text-blue-500" },
    { text: "in" },
    { text: "need" },
  ],
  [
    { text: "Listen" },
    { text: "attentively" },
    { text: "to" },
    { text: "someone", className: "text-blue-500 dark:text-blue-500" },
    { text: "who" },
    { text: "needs" },
    { text: "to" },
    { text: "talk", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Give" },
    { text: "compliments" },
    { text: "to" },
    { text: "your" },
    { text: "coworkers", className: "text-blue-500 dark:text-blue-500" },
    { text: "or" },
    { text: "classmates", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Leave" },
    { text: "positive" },
    { text: "sticky" },
    { text: "notes" },
    { text: "around" },
    { text: "your" },
    { text: "community", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Donate" },
    { text: "blood" },
    { text: "or" },
    { text: "plasma" },
    { text: "to" },
    { text: "a" },
    { text: "local" },
    { text: "blood", className: "text-blue-500 dark:text-blue-500" },
    { text: "bank", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Donate" },
    { text: "food" },
    { text: "to" },
    { text: "a" },
    { text: "local" },
    { text: "food", className: "text-blue-500 dark:text-blue-500" },
    { text: "bank", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Write" },
    { text: "a" },
    { text: "thank-you" },
    { text: "letter" },
    { text: "to" },
    { text: "someone" },
    { text: "who" },
    { text: "has" },
    { text: "made" },
    { text: "a" },
    { text: "difference", className: "text-blue-500 dark:text-blue-500" },
    { text: "in" },
    { text: "your", className: "text-blue-500 dark:text-blue-500" },
    { text: "life", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Offer" },
    { text: "to" },
    { text: "walk" },
    { text: "a" },
    { text: "neighbor's" },
    { text: "dog", className: "text-blue-500 dark:text-blue-500" },
    { text: "or" },
    { text: "pet", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Leave" },
    { text: "a" },
    { text: "generous" },
    { text: "tip" },
    { text: "for" },
    { text: "your" },
    { text: "server", className: "text-blue-500 dark:text-blue-500" },
    { text: "or" },
    { text: "delivery", className: "text-blue-500 dark:text-blue-500" },
    { text: "person", className: "text-blue-500 dark:text-blue-500" },
  ],
  [
    { text: "Offer" },
    { text: "to" },
    { text: "help", className: "text-blue-500 dark:text-blue-500" },
    { text: "a" },
    { text: "friend" },
    { text: "move" },
    { text: "or" },
    { text: "unpack" },
    { text: "after" },
    { text: "a" },
    { text: "move" },
  ],
  [
    { text: "Support" },
    { text: "local" },
    { text: "small" },
    { text: "businesses" },
    { text: "by" },
    { text: "writing" },
    { text: "positive" },
    { text: "reviews", className: "text-blue-500 dark:text-blue-500" },
    { text: "and" },
    { text: "referring", className: "text-blue-500 dark:text-blue-500" },
    { text: "friends" },
  ],
  [
    { text: "Offer" },
    { text: "a" },
    { text: "listening", className: "text-blue-500 dark:text-blue-500" },
    { text: "ear" },
    { text: "to" },
    { text: "someone" },
    { text: "who" },
    { text: "is" },
    { text: "going" },
    { text: "through" },
    { text: "a" },
    { text: "difficult" },
    { text: "time" },
  ],
  [
    { text: "Send" },
    { text: "a" },
    { text: "care", className: "text-blue-500 dark:text-blue-500" },
    { text: "package", className: "text-blue-500 dark:text-blue-500" },
    { text: "to" },
    { text: "a" },
    { text: "friend" },
    { text: "who" },
    { text: "is" },
    { text: "feeling" },
    { text: "down" },
  ],
  [
    { text: "Give" },
    { text: "up" },
    { text: "your", className: "text-blue-500 dark:text-blue-500" },
    { text: "seat", className: "text-blue-500 dark:text-blue-500" },
    { text: "on" },
    { text: "public" },
    { text: "transportation" },
    { text: "to" },
    { text: "someone" },
    { text: "who" },
    { text: "needs" },
    { text: "it" },
  ],
  [
    { text: "Teach", className: "text-blue-500 dark:text-blue-500" },
    { text: "someone" },
    { text: "a" },
    { text: "new" },
    { text: "skill" },
    { text: "or" },
    { text: "share" },
    { text: "your" },
    { text: "knowledge" },
    { text: "with" },
    { text: "others" },
  ],
];

export default RAKS;
